# Generated by Django 2.1.5 on 2019-02-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(help_text='order to display entries')),
                ('description', models.TextField(help_text='short description of an aspect of the position')),
            ],
            options={
                'verbose_name': 'Position Detail',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('url_name', models.CharField(help_text='String to display in URL. Must be unique', max_length=30, unique=True, verbose_name='URL Name')),
                ('title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.PositiveSmallIntegerField(verbose_name='Zip Code')),
                ('summary', models.TextField(help_text='One or two paragraphs summarizing your goals, history, and skills.')),
                ('hook', models.TextField(help_text='short blurb or tag line')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='One or two word skill name. Try to reuse first.', max_length=100, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook', models.TextField(help_text='short description of position')),
                ('org_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('org_description', models.CharField(max_length=200, verbose_name='Organization Description')),
                ('org_city', models.CharField(max_length=100, verbose_name='Organization City')),
                ('org_state', models.CharField(max_length=100, verbose_name='Organization State')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('current', models.BooleanField(default=False, verbose_name='Current Position')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('title', models.CharField(max_length=200, verbose_name='Position Title')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Resume')),
            ],
            options={
                'verbose_name_plural': 'Work Histories',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='positions',
            field=models.ManyToManyField(to='cv.WorkHistory'),
        ),
        migrations.AddField(
            model_name='positiondetail',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.WorkHistory'),
        ),
    ]
